- platform: samsungtv
  host: 192.168.2.150
- platform: plex
  host: 192.168.2.110
  port: 32400
- platform: spotify
  client_id: !secret client_spotify
  client_secret: !secret spotify_secret
- platform: snapcast
  host: 192.168.2.116
- platform: mpd
  host: 192.168.2.116
  port: 6602  
- platform: volumio
  host: 192.165.2.119
  port: 3000
