- platform: rfxtrx
  automatic_add: True
  signal_repetitions: 2
  devices:
    0b11000001517ba202010f80:
      name: Markis 
    0b11000a01517ba201010f70:
      name: Philips LedKlot

#- platform: mqtt
#  name: "Plafond server rum"
#  command_topic: "cmnd/serv/power"
#  state_topic: "stat/serv/POWER"
#  qos: 1
#  payload_on: "ON"
#  payload_off: "OFF"
#  retain: true
  
- platform: broadlink
  host: 192.168.2.103
  mac: B4:43:0D:38:FB:34
  timeout: 15
  switches:
    logitech_upp:
      friendly_name: "Volym UPP Logitech"
      command_on: 'JgBQAAABJZMUEhQ2EhEUERQRFBEUERQSExITEhMTEhITEhM2FRETNhMSEzYUERQ2ExITNhQRFDcTNRQRFDYTEhU1ExITNhQTEwAFEwABJUsSAA0FAAAAAAAAAAA='
    logitech_ner:  
      friendly_name: "Volym NER Logitech"
      command_on: 'JgBgAAABJpITEhM3ExITEhMSExIUERUQExITEhMSFhASExI2FRISNhMSEzYUERQ3EhIUNRQ2ExMSNxMSEzYTExM2ExIUERQ1FQAFEwABJUoVAAz1AAElShMADPgAASVJFQANBQAAAAAAAAAA'
    logitech_effect:
      friendly_name: "Effect Logitech"
      command_on: 'JgBYAAABJpMSEhU1ExEUEhMRFRAUERQRFBEUExIRFBITERQ2FRATNhQSEzYVNRQ1ExITEhUQExITOBISExITEhM2FDYUNxI2EwAFFQABJUoTAAz3AAElShMADQU='
    logitech_input:  
      friendly_name: "Input Logitech"
      command_on: 'JgBQAAABJZMVERI2FBEVEBQRFBEUEhMSExITEhMSExITEhM2FBEUNhMSFBETEhQ1FBITERQRFBMSOBE4EjYTEhY1EjYTNxM2FQAFEwABJkkTAA0FAAAAAAAAAAA='
    logitech_on:  
      friendly_name: "ON Logitech"
      command_on: 'JgBUAA0AAZcAASWUEhQSNRQTExITERMTEhIVEBMTExETEhMSExITOBIRFDYTEhMSExITEhQRFBEUEhQ0FDYUNhQ2EzYUNRQ2EzcTERQABRQAASZJEwANBQAAAAA='
    logitech_off:
      friendly_name: "OFF Logitech"
      command_on: 'JgBYAAABJJQSEhM2FBITERQSExITERQSExMSERUQFBEUEhQ1FBEUNhMSExITEhMSExIUEhISFDYTNhM2FDYTNhU2EjYVNRMTEgAFFgABJUkTAAz3AAElShQADQU='
    samsung_source:
      friendly_name: "Source Samsung"
      command_on: 'JgAwApKXEDYUNhI2ExQTERMSEhMTEhQ0FDYSNxIUEhITEhQQFBMTNhETEhEUFBISExETERUSExETNhM1FDcTNRQ3ETYUNRMABgiTlBM2EzYTNxITExEUEhMQExMTNhM2EzUUExISExITEhITEzcSEhMRExMTEhQRExESFBMREzYTNhM4EjYTNxI1FDUTAAYIlJQTNhQ0EzYTExMRFBMRExEUFDQTNxM0FBMTERQRExISFBM2EhITERMUFBAUERMRExQTEBQ3ETYUNxQ0FDYSNRU2EgAGCJSTFDQVNRM1ExQSEhMSEhITExM1FDcRNhMTExITEhMRExMTNxISEhEVEhISExITERMTFRATNhI2FDcSNhQ1FDUUNRIABgmTlhE2FDYSNhMUExETERMRExMTNhM2EjYUFBIRFBESEhMTEjcTERQRExMUERMSEhISFBMSEjYTNRU2EzYTNhI2FDUTAAYJk5QSNxI3EzQUExMRFRESEhMTEjYUNRM1FBMTERQRExETExM4ERITERMUEhITEhQQExMTEhM3ETYTOBI2EzYTNhM2EgAGCZOUFDQUNRM2ExQSEhMSEhISFBM1FDcRNhMTFBETEhISFBISNxMRFBISExMRFBEUEBMTFBAUNhM1EzkTNBQ2FDQTNhIABgmTlBM2EzYTNRMUEhMRFBMQExQSNRQ2EzcRFBMRFBETERMTEzYTERQRExMUERMTERISFBQQEzYTNRM4FDQVNRI2EzcSAA0FEhITEhISExM='
    samsung_channel_up:
      friendly_name: "Kanal UPP"
      command_on: 'JgDSAJOVEjYTNhI2FBMSEhMTEhETExM1FDcSNRQTEhIUERMRExMTERM2FBISExM1ExMSEhEWEDgSEhI2EzgTERQ2EjYTNhIABgmSlRI4EjYSNhMUEhITEhISExMSNxI3EjYTFBMRExISEhIWERETNxISEhQTNhMSEhMRFBI3EhISNxI5EhITNhI2EzcRAAYKkpUSNxI2EjcSFRISEhMSEhMUEzQUNxE2ExQTEhISEhITExMREzYVEBMSFDUUERMSEhMTNxISEjYUNxQQFDUTNhU0FAANBQAAAAAAAA=='
    samsung_channel_down:
      friendly_name: "Kanal NER"    
      command_on: 'JgDSAJKUEzYUNRM1FBMTERQRFBATExQ2EzYRNhMUEhITEhMREhQTEhISExETExM3ExITEREWETYTNhI3EjgTEhI3EjcSNhIABgmSlRI2FDYTNRQTERURFBATERURORA3ETgRFhAUERMRExIUEhQRFBESEhQSNhMSEhMRFBM4EDkQNxI4ExISNxE3EjcSAAYJk5QSNhM2EzYSFBITEhMSEhIUETcUNRI3EhQSEhMTERMRFBQSExESEhIUEzYTEhMREhQSNxI3ETcTOBISEjcSOBE3EQANBQAAAAAAAA=='  