
  

- platform: mqtt
  state_topic: 'office/sensor1'
  name: 'Temperatur'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temperature }}'

- platform: mqtt
  state_topic: 'office/sensor1'
  name: 'Fuktighet'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'
 
