- platform: generic
  name: Mattias
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.mattuesoitz.attributes.latitude }},{{ states.device_tracker.mattuesoitz.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.mattuesoitz.attributes.latitude }},{{ states.device_tracker.mattuesoitz.attributes.longitude }}
  limit_refetch_to_url_change: true
  
- platform: generic
  name: Marie
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.ru.attributes.latitude }},{{ states.device_tracker.ru.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.ru.attributes.latitude }},{{ states.device_tracker.ru.attributes.longitude }}
  limit_refetch_to_url_change: true
  